#############################################################################
                       ###Test project Login###
                       
PARABANK_Login_Username=//input[@class='input' and @name= 'username']
PARABANK_Login_Password=//input[@class='input' and @name= 'password']
PARABANK_Login_LoginButton=//input[@class='button' and @value= 'Log In']
PARABANK_Open_New_Account=//a[@href = '/parabank/openaccount.htm']
PARABANK_Select_Account_Type=//*[@id="type"]
PARABANK_Select_Choose_Existing_Account=//*[@id="fromAccountId"]
PARABANK_button_Open_New_Account=//input[@class= 'button']
PARABANK_AccountDetail_New_Account_Number=//*[@id="newAccountId"]
PARABANK_New_Account_Number=//*[@id="newAccountId"]
PARABANK_AccountDetail_Account_Type=//*[@id="accountType"]
PARABANK_AccountDetail_Account_Balance=//*[@id="balance"]
PARABANK_AccountDetail_Account_Available_Balance=//*[@id="availableBalance"]

PARABANK_Open_Bill_Pay=/html/body/div[1]/div[3]/div[1]/ul/li[4]/a
PARABANK_BillPay_PayeeName=//input[@class='input ng-pristine ng-valid ng-empty ng-touched']
PARABANK_BillPay_Address=//input[@class='input ng-pristine ng-untouched ng-valid ng-empty' and @name ='payee.address.street']
PARABANK_BillPay_City=//input[@class='input ng-pristine ng-untouched ng-valid ng-empty' and @name ='payee.address.city']
PARABANK_BillPay_State=//input[@class='input ng-pristine ng-untouched ng-valid ng-empty' and @name ='payee.address.state']
PARABANK_BillPay_ZipCode=//input[@class='input ng-pristine ng-untouched ng-valid ng-empty' and @name ='payee.address.zipCode']
PARABANK_BillPay_PhoneNo=//input[@class='input phone-number-f840d29e-9492-4ec1-918a-07571acb0f2d ng-pristine ng-untouched ng-valid ng-empty' and @name ='payee.phoneNumber']
PARABANK_BillPay_AccountNo=//input[@class='input ng-pristine ng-untouched ng-valid ng-empty' and @name ='payee.accountNumber']
PARABANK_BillPay_Verify_AccountNo=//input[@class='input ng-pristine ng-untouched ng-valid ng-empty' and @name ='verifyAccount']
PARABANK_BillPay_Amount=//input[@class='input ng-pristine ng-untouched ng-valid ng-empty' and @name ='amount']
PARABANK_BillPay_From_Account=//select[@class='input ng-valid ng-not-empty ng-touched ng-dirty ng-valid-parse']
PARABANK_BillPay_SendPayment=//input[@class='button' and @value='Send Payment']
PARABANK_Open_Account_Overview=//a[@href = '/parabank/overview.htm']
PARABANK_AccountOverview_From_Account=//a[@href = 'activity.htm?id=14010']
PARABANK_AccountActivity_Transaction=//div[@ng-if='showActivity']/h1[@class= 'title']
PARABANK_AccountOverview_To_Account=//a[@href = 'activity.htm?id=13899']
























